{
  "domain": "google.sk",
  "status": [],
  "dates": {
    "created": null,
    "updated": null,
    "expires": "2019-07-24T00:00:00Z"
  },
  "nameservers": [
    "ns1.google.com",
    "ns2.google.com",
    "ns3.google.com",
    "ns4.google.com"
  ],
  "dnssec": null,
  "registrar": {
    "email": "domains@fajnor.sk",
    "name": "FAJN-0002, FAJNOR IP s. r. o.",
    "street": "Krasovského 13",
    "city": "Bratislava",
    "postal_code": "851 01",
    "state": null,
    "country": "SK",
    "organization": "FAJNOR IP s. r. o.",
    "phone": "+421.263811927",
    "fax": null,
    "handle": null
  },
  "contacts": {
    "registrant": {
      "email": null,
      "name": "Google",
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "administrative": {
      "email": null,
      "name": "Google",
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "technical": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "billing": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "abuse": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    }
  }
}