{
  "domain": "google.com.ua",
  "status": [
    "clientDeleteProhibited",
    "clientTransferProhibited",
    "clientUpdateProhibited",
    "ok",
    "linked"
  ],
  "dates": {
    "created": "2002-12-04T00:00:00+02:00",
    "updated": "2018-11-02T11:29:08+02:00",
    "expires": "2019-12-04T00:00:00+02:00"
  },
  "nameservers": [
    "ns3.google.com",
    "ns1.google.com",
    "ns4.google.com",
    "ns2.google.com"
  ],
  "dnssec": null,
  "registrar": {
    "email": null,
    "name": "ua.markmonitor",
    "street": null,
    "city": "Meridian, Idaho",
    "postal_code": null,
    "state": null,
    "country": "US",
    "organization": "MarkMonitor Inc.",
    "phone": null,
    "fax": null,
    "handle": null
  },
  "contacts": {
    "registrant": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "administrative": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "technical": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "billing": {
      "email": null,
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    },
    "abuse": {
      "email": "abusecomplaints@markmonitor.com",
      "name": null,
      "street": null,
      "city": null,
      "postal_code": null,
      "state": null,
      "country": null,
      "organization": null,
      "phone": null,
      "fax": null,
      "handle": null
    }
  }
}